### ISSUE TITLE
Unbalanced save/restore state operators.

### ISSUE THREAD

**Issue by nsarathk** [itext/itextpdf#12]
my Code consists of creating a horizontal line 
```
LineSeparator horizontalLineSeperator = new LineSeparator();
horizontalLineSeperator.setOffset(1f);
horizontalLineSeperator.setLineWidth(125f);
horizontalLineSeperator.setAlignment(Element.ALIGN_MIDDLE);
```
with which at the end whenever i try to close the document with `document.close();` its throwing me Unbalanced save/restore state operator exception. Kindly let me know what is the actual problem in it.

**Comment by amedee** [comment]
For Professional Support, please see http://itextpdf.com/support
For Community Support, please ask your question on StackOverflow: http://stackoverflow.com/questions/tagged/itextpdf
