### ISSUE TITLE
XMLWorker table page-break-inside: avoid not working

### ISSUE THREAD

**Issue by BillTheGoat** [itext/itextpdf#14]
`<table style="page-break-inside: avoid;"> ... </table> `

does _not_ cause a page break as expected

[internal itext code](https://github.com/itext/itextpdf/blob/1fb08dc7998c15b1bbc550ad3d34d6a97e0ed9cc/xmlworker/src/main/java/com/itextpdf/tool/xml/html/table/Table.java):

```
for (Entry<String, String> entry : tag.getCSS().entrySet()) {
				if (entry.getKey().equalsIgnoreCase(CSS.Property.PAGE_BREAK_INSIDE)) {
					if (entry.getValue().equalsIgnoreCase(CSS.Value.AVOID)) {
						table.setKeepTogether(true);
					}
				}
			}
```

But:

```
<div style="page-break-inside: avoid;">
<table>...</table>
</div>
```
_does_ cause a page break as expected

Nested tables do not work:

```
<div style="page-break-inside: avoid;">
<table>
<tr><td>
     <div style="page-break-inside: avoid;">
          <table>... to keep together ... </table>
     </div>
</td></tr>
</table>
</div>
```
does _not_ cause a page break as expected

**Comment by amedee** [comment]
Thank you for reporting this. Are you the same person who also reported this in our JIRA as SUP-1398?

**Comment by BillTheGoat** [comment]
No. I saw a question on StackOverflow, but it was attempting to apply this to tr/tds, while I am trying to use your existing table code. Basic goal: have a table with two nested tables to simulate float:left / float:right; and keep it all on one page.

**Comment by amedee** [comment]
What is the link to that StackOverflow question? In case the issues are related.

**Comment by BillTheGoat** [comment]
[This one](http://stackoverflow.com/questions/35283892/itext-prevent-row-breaking-across-multiple-pages-using-xml-worker)

**Comment by BillTheGoat** [comment]
The last example with the nesting may or may not be related to another (odd!) issue related to image scaling that has come up while looking for a work around on this one.

One of the cells in each table has an image. I am manually setting the size of this image in a custom tag handler. I am setting the image size like:
```
w = 222;
h = img.getPlainHeight() * (w/img.getPlainWidth());
```
If the image fits on the current page, or if it is "`far enough`" down the page to automagically trigger a page break before it, it is the right size (almost ... get back to that). However, if "`juuusst the right amount`" of that image fits on the current page, instead of triggering a page break before, the image will be automagically resized, and be even much smaller than how it would appear otherwise (less than 50% the size) (sic!).  I am pretty sure an image should never be resized without explicit code...

This remains true even if I take the image out of all tables, so that my structure is:

```
<div>
     <img />
     <img />
</div>
<div>
     <img />
     <img />
</div>
```
I can toggle this behavior simply by rotating the images in the first table-in-div/plain div before processing, so that the space for the second table-in-div/plain div on the current page is reduced.

So: the "almost" the right size of the original I mentioned is that there is a similar resizing occurring on one particularly tall image (from cellphone held wrong) even without this, but it is perhaps 15% smaller instead of the 50%. I cannot see anything that might require the resizing in the image or page format, etc.,  and I have not found any indications of why this might happen from the itext source code. The entire thing is just bizarre.

I am sending you two pdfs via email demonstrating this. They have random personal photos from my phone for testing and I do not want them online...

 I  can delete this comment and open a second issue if you think I should.

**Comment by amedee** [comment]
Please do not send files via email. Put them on a public file sharing site like Dropbox. We can only keep files confidential if they are from customers with a support contract. They have access to our JIRA. Anything else is Community Support, as Open Source. That means code as well as files.
To which address did you send the files?

**Comment by BillTheGoat** [comment]
Have not sent yet. I will try to make something for public consumption.

**Comment by BillTheGoat** [comment]
[Files showing Image Errors](http://wikisend.com/download/318518/ImageSizeBugs.zip). Only the landscape images actually have the correct width. The two smaller image files change the jump based on a 5 or 6 line comment above the images.

**Comment by amedee** [comment]
I suggest that you ask this as a question on StackOverflow: http://stackoverflow.com/questions/tagged/itext

See this page for more information about iText Community Support: http://itextpdf.com/support

**Comment by BillTheGoat** [comment]
Are you stating that this is not a bug and Itext by design randomly resizes images?! You guys are unbelievable.

**Comment by amedee** [comment]
No, just that we do Community Support only on StackOverflow. That is where most of the iText users are.
Customers with a support contract have access to our JIRA and get responses from the developers directly. (I'm not a developer by the way)

**Comment by BillTheGoat** [comment]
I posted here instead of SO because you specifically state on your website to post here if something is clearly a bug. This fit the bill to me... I will post there, but it is a bit hard to get me to pay for a support contract (which I am evaluating) if you guys have zero game dealing with obvious flaws in one of the most core features of any pdf generation process. 

I would love to offer an offline pdf option for my users, but If I can't get up and running, why would I pay?

**Comment by amedee** [comment]
To summarize your issue: a table only breaks when it is wrapped inside a div, and nested tables don't break.
I'm not a developer, but to this QA's ears it sounds more like missing features. You could implement the missing features yourself by extending iText, and submit a pull request when you're done. The best place to ask help for extending iText really is StackOverflow. I know several people on StackOverflow, many of them who aren't iText Software employees but users like yourself, who have experience in extending iText and who can certainly help you out.
I'm in the technical team, not in the sales team, and I really don't want to get into an online argument about the cost of a license which includes tech support. I hope you can understand that. Hey, I've been using open source software myself for decades before I joined iText, so on a personal level I can empathize with your issue. But it's the license fees that pay the wages of the developers, and you can be damn well sure that the dev team takes great pride in having a very high solution rate for our customers.

**Comment by BillTheGoat** [comment]
And things get resized randomly, which means that my workarounds can only go so far. I rewrote my entire table code to create a single image with all data embedded via an extension function, and the resize problem just killed that effort.

And from where I sit,  I am not a sure as you that things do get resolved. 

Why would I be? My issue is not the price, it is that things you state work don't (it is stated that keep-together works for tables, and that image width and height are set regularly and not sporadically when I define them in my java code using `img.scaleAbsolute(w, h);`),  _and_ there is no effort to get them working. 

Why do you guys think that people should trust you when using _your_ requested channels for things _you_ claim are part of _your_ features invariably result in a "not our problem" response?

I agree with you that none of us have the time to debate here, especially since I know you are instructed to deal with things in a certain way. But I hope you collectively might re-evaluate your reaction to bugs; and rendering contrary to stated functionality is a bug, even if extending itext further for yet another a workaround might resolve it.

**Comment by blowagie** [comment]
I'm new to this conversation and the rant makes it difficult to read, but wasn't this problem explained and solved a long time ago on StackOverflow? See http://stackoverflow.com/questions/21589209/itextsharp-image-minimum-table-cell-height

Whether or not we should bill the goat, I don't care, but the goat should have posted a SSCCE on StackOverflow so that we can determine if he's experiencing a bug or if it's just a matter of changing the default (and expected) behavior of iText.
