### ISSUE TITLE
Changing Phrase Font after constructing PdfPCell

### ISSUE THREAD

**Issue by jmielkeway** [itext/itextpdf#16]
It seems if I do something like `PdfPCell someCell = new Cell(new Phrase(someString))`, and then try something like `someCell.getPhrase.setFont(someNewFont)`, and I do all this before adding the cell to the `PdfPTable`, the cell will not have the correct font. Instead, I must construct the cell with the font already in the cell in order to get the correct font:
```
Phrase somePhrase = new Phrase(someString, someFont);
PdfPCell someCell = new PdfPCell(somePhrase);

```
This is slighly annoying, because if I do the former way, my tests still pass after testing attributes of the font returned from `someCell.getPhrase().getFont()...`

**Comment by amedee** [comment]
Hello and thank you for opening this issue. I'd like to point you to our support page http://itextpdf.com/support and in particular this part:

> **Where to post what type of question**
> 
> * How do I... ? - StackOverflow's [iText](http://stackoverflow.com/questions/tagged/itext) or [iTextSharp](http://stackoverflow.com/questions/tagged/itextsharp) topics.
> * I got this error, why? - StackOverflow's [iText](http://stackoverflow.com/questions/tagged/itext) or [iTextSharp](http://stackoverflow.com/questions/tagged/itextsharp) topics.
> * I got this error and I'm sure it's a bug - File an issue on GitHub's [iText](http://github.com/itext/itextpdf/issues) or [iTextSharp](http://github.com/itext/itextsharp/issues) issue pages.
> * I have an idea/request - File an issue on GitHub's [iText](http://github.com/itext/itextpdf/issues) or [iTextSharp](http://github.com/itext/itextsharp/issues) issue pages.
> * When will you...? - Send an e-mail to [sales@itextpdf.com](sales@itextpdf.com)!

You are more than welcome to ask your question on StackOverflow.
