### ISSUE TITLE
Getting chunk width is not returning the correct value

### ISSUE THREAD

**Issue by vincpa** [itext/itextpdf#18]
Calling chunk.GetWidthPoint() is returning an incorrect value when calculating the width.

See supporting StackOverflow question.
http://stackoverflow.com/questions/37475437/getting-the-width-of-a-chunk-does-not-include-the-last-character

Although the reason might be due to "rounding errors" I would expect the correct value to be returned.

**Comment by amedee** [comment]
^ The above commit is unrelated to this issue. It's just a coincidence that there is an iTextSharp pull request with the same ID.

**Comment by amedee** [comment]
Thank you for asking your question on StackOverflow. We'll close the issue here.
